[project]
name = "ConfTools-z7"
version = "7.2"
readme = "README.md"
description = ""
authors = [{name = "Andrea Censi", email = "AndreaCensi@users.noreply.github.com"}]
dependencies = [
    "PyYAML",
    "setuptools",
    "zuper-commons-z7",]

[project.optional-dependencies]
test = [
    ]

[tool.poetry]
name = "ConfTools-z7"
version = "7.2"
description = ""
authors = ["Andrea Censi <AndreaCensi@users.noreply.github.com>"]
packages = [
    {from = "src", include = "conf_tools"},
    {from = "src", include = "conf_tools/utils"},
    ]

[tool.poetry.dependencies]
PyYAML = "*"
setuptools = "*"
zuper-commons-z7 = "*"

[tool.poetry.group.test.dependencies]
python = ">=3.12"

[build-system]
requires = [
    "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"
